// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoY0JhKKidMHpK-o5NRdXUoTJhs2B65-U',
    appId: '1:1080250705358:web:5fcb6b4eddb02fec3d379f',
    messagingSenderId: '1080250705358',
    projectId: 'trainingcourse-c7552',
    authDomain: 'trainingcourse-c7552.firebaseapp.com',
    storageBucket: 'trainingcourse-c7552.appspot.com',
    measurementId: 'G-3Z9NJKMDE5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTwllhRWuI_CU9lxPDh1zZtuRWvKAli2o',
    appId: '1:1080250705358:android:7bd9d3c547b016213d379f',
    messagingSenderId: '1080250705358',
    projectId: 'trainingcourse-c7552',
    storageBucket: 'trainingcourse-c7552.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-ACGiFvum_FWqix3SdNIx1B0ty5CFm38',
    appId: '1:1080250705358:ios:71fd4b33db6042fc3d379f',
    messagingSenderId: '1080250705358',
    projectId: 'trainingcourse-c7552',
    storageBucket: 'trainingcourse-c7552.appspot.com',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-ACGiFvum_FWqix3SdNIx1B0ty5CFm38',
    appId: '1:1080250705358:ios:71fd4b33db6042fc3d379f',
    messagingSenderId: '1080250705358',
    projectId: 'trainingcourse-c7552',
    storageBucket: 'trainingcourse-c7552.appspot.com',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoY0JhKKidMHpK-o5NRdXUoTJhs2B65-U',
    appId: '1:1080250705358:web:81a583604ab23d1b3d379f',
    messagingSenderId: '1080250705358',
    projectId: 'trainingcourse-c7552',
    authDomain: 'trainingcourse-c7552.firebaseapp.com',
    storageBucket: 'trainingcourse-c7552.appspot.com',
    measurementId: 'G-7KMLWLMJQH',
  );
}
